FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/server/package.json ./
RUN npm install
COPY apps/server ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 4000
CMD ["node", "dist/main.js"]
